image: alpine:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

stages:
  - validation
  - test
  - snapshot
  - release

pylint:
  stage: validation
  script:
    - apk add --update --no-cache python3-dev gcc libc-dev libffi-dev
    - ln -sf python3 /usr/bin/python
    - ln -sf pip3 /usr/bin/pip
    - python -m ensurepip
    - python -m pip install --no-cache --upgrade pip setuptools pylint
    - python -m pylint --version
    - PYTHONPATH=${PYTHONPATH}:$(dirname %d) python -m pylint scripts/ci.py

eslint:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
  script: echo 'eslint happens here'
  artifacts:
    when: always
    expire_in: 3 day
    paths:
      - '*.log'
  except:
    - tags

unit_tests:
  stage: test
  script: echo 'unit tests happen here'

npm_publish_snapshot:
  stage: snapshot
  script: echo 'publish snapshot happens here'

