image: stevewhitmore/nodejs-python

stages:
  - validation
  - test
  - snapshot
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

# pylint:
#   stage: validation
#   script:
#     - python -m pylint --version
#     - PYTHONPATH=${PYTHONPATH}:$(dirname %d) python -m pylint scripts/ci.py

# eslint:
#   stage: test
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}
#   script:
#     - python scripts/ci.py eslint
#   except:
#     - tags

# unit_tests:
#   stage: test
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}
#   script:
#     - python scripts/ci.py unit_tests

npm_publish_snapshot:
  stage: snapshot
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - python scripts/ci.py publish_snapshots
