image: stevewhitmore/nodejs-python

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

stages:
  - validation
  - test
  - snapshot
  - release

pylint:
  stage: validation
  script:
    - python -m pylint --version
    - PYTHONPATH=${PYTHONPATH}:$(dirname %d) python -m pylint scripts/ci.py

eslint:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  script:
    - python scripts/ci.py eslint
  artifacts:
    when: always
    expire_in: 3 day
    paths:
      - '*.log'
  except:
    - tags

unit_tests:
  stage: test
  script:
    - python scripts/ci.py unit_tests

npm_publish_snapshot:
  stage: snapshot
  script:
    - echo "_auth=${NPM_TOKEN}" > .npmrc
    - python scripts/ci.py publish_snapshot
