name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: stevewhitmore/nodejs-python

    steps:
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Lint
        run: python scripts/ci.py eslint

      - name: Unit Tests
        run: python scripts/ci.py test

      - name: Publish Snapshots
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          python scripts/ci.py publish_snapshots
